/**
 * Generates docs/database/DATA-DICTIONARY.md from the migrated catalog (add-on 11 item 26), so the column-level
 * dictionary always matches the schema. Usage (from backend/): deno task db:dictionary
 */
import { loadMigrations, migrate } from '../../src/db/migrate.ts';
import { openPglite } from '../../src/db/pglite.ts';

const OUT = new URL('../../../docs/database/DATA-DICTIONARY.md', import.meta.url);

/** Copies of facts kept elsewhere (01 §1.6 register): column → its source of truth. */
const SOURCE_OF_TRUTH: Record<string, string> = {
  'journal_line.entity_id': 'journal.entity_id (composite FK)',
  'journal_line.value_date': 'journal.value_date (composite FK)',
  'txn_entity.value_date': 'txn.value_date (composite FK, ON UPDATE CASCADE)',
  'balance_current.balance_enc': 'Σ journal_line of the slice (Integrity Verifier)',
  'balance_period.debits_enc': 'Σ journal_line Dr of the slice in the period',
  'balance_period.credits_enc': 'Σ journal_line Cr of the slice in the period',
  'balance_period.closing_enc': 'opening + movements, fixed at close',
  'open_item.remaining_enc': 'original_enc − Σ settlement_allocation',
  'open_item.item_status': 'derived from remaining_enc',
  'journal_line.holder_person_id': 'location_holder at posting time',
  'txn_leg.amount_bidx': 'txn_leg.amount_enc',
  'txn_leg.amount_bucket': 'txn_leg.amount_enc',
  'balance_current.entity_id': 'balance_slice.entity_id (composite FK)',
  'balance_period.entity_id': 'balance_slice.entity_id (composite FK)',
};

/** Meanings shared by every table that has the column (03-schema.md conventions). */
const STANDARD: Record<string, string> = {
  id: 'Stable identifier (UUIDv7); never a name',
  version: 'Optimistic-concurrency version, incremented on every update',
  created_at: 'When the row was created',
  created_by: 'User who created the row',
  updated_at: 'When the row last changed',
  change_xid: 'Transaction that last wrote the row; mobile delta-sync cursor (06 §6.6)',
  key_version: 'Version of the derived key that encrypted the ciphertext in this row',
  status: 'Lifecycle: active, inactive (no new use), archived',
  reason: 'Why, in plain words',
};

function sensitivity(table: string, column: string, type: string): string {
  if (/^(password_hash|mpin_hash|token_hash|code_hash)$/.test(column)) return 'S — one-way hash, never readable';
  if (column.endsWith('_enc')) return 'C — encrypted (AES-256-GCM, keys outside the database)';
  if (/(_bidx|_bucket|username_hash|content_hash|verification_hash|row_hash|prev_hash)$/.test(column)) {
    return 'H — keyed hash or integrity hash';
  }
  if (type === 'inet' || column === 'user_agent' || column === 'email') return 'R — personal data';
  if (['reason', 'display_name', 'legal_name', 'name', 'address', 'description', 'summary'].includes(column)) {
    return 'R';
  }
  return table === 'schema_migration' ? 'P' : '';
}

/** Renders the dictionary from a freshly migrated database. */
export async function renderDictionary(): Promise<string> {
  const { db, sql } = await openPglite();
  await migrate(sql, await loadMigrations(new URL('../migrations/', import.meta.url)));
  const q = async <T>(text: string, params: unknown[] = []) => (await db.query<T>(text, params)).rows;

  const tables = await q<{ oid: number; name: string; comment: string | null }>(
    `select c.oid::int as oid, c.relname as name, obj_description(c.oid, 'pg_class') as comment
   from pg_class c join pg_namespace n on n.oid = c.relnamespace
   where n.nspname = 'finly' and c.relkind = 'r' order by c.relname`,
  );
  const esc = (s: string | null) => (s ?? '').replaceAll('|', '\\|').replaceAll('\n', ' ');

  let md = `# Data dictionary (generated)

Generated by \`deno task db:dictionary\` from the migrated schema — do not edit by hand. Design-level descriptions,
relationships and reasons are in [03-schema.md](03-schema.md); this file is the exact column-level truth.

Sensitivity: **C** encrypted · **H** keyed or integrity hash · **S** one-way secret hash · **R** plaintext,
row-level-security restricted / personal data · blank = non-sensitive structure. Every table has row-level security
enabled. Tables: ${tables.length}.

`;

  for (const t of tables) {
    const cols = await q<
      { name: string; type: string; notnull: boolean; def: string | null; comment: string | null; gen: string }
    >(
      `select a.attname as name, format_type(a.atttypid, a.atttypmod) as type, a.attnotnull as notnull,
            pg_get_expr(d.adbin, d.adrelid) as def, col_description(a.attrelid, a.attnum) as comment,
            a.attgenerated::text as gen
     from pg_attribute a left join pg_attrdef d on d.adrelid = a.attrelid and d.adnum = a.attnum
     where a.attrelid = $1 and a.attnum > 0 and not a.attisdropped order by a.attnum`,
      [t.oid],
    );
    const fks = await q<{ col: string; ref: string }>(
      `select a.attname as col, confrelid::regclass::text as ref
     from pg_constraint c join pg_attribute a on a.attrelid = c.conrelid and a.attnum = c.conkey[1]
     where c.conrelid = $1 and c.contype = 'f'`,
      [t.oid],
    );
    const fkOf = new Map(fks.map((f) => [f.col, f.ref.replace('finly.', '')]));
    const cons = await q<{ name: string; type: string; def: string }>(
      `select conname as name, contype::text as type, pg_get_constraintdef(oid) as def from pg_constraint
     where conrelid = $1 order by contype, conname`,
      [t.oid],
    );
    const idx = await q<{ def: string }>(
      `select pg_get_indexdef(i.indexrelid) as def from pg_index i where i.indrelid = $1 and not i.indisprimary
     order by 1`,
      [t.oid],
    );
    const pols = await q<{ name: string; cmd: string; roles: string[] }>(
      `select policyname as name, cmd, roles from pg_policies where schemaname = 'finly' and tablename = $1 order by 1`,
      [t.name],
    );
    const trg = await q<{ fn: string }>(
      `select p.proname as fn from pg_trigger g join pg_proc p on p.oid = g.tgfoid
     where g.tgrelid = $1 and not g.tgisinternal`,
      [t.oid],
    );
    const fns = new Set(trg.map((r) => r.fn));
    const lifecycle = [
      fns.has('tg_immutable') || fns.has('tg_journal_line_immutable') ? 'append-only (no update or delete)' : '',
      fns.has('tg_no_delete') ? 'never deleted' : '',
      fns.has('tg_history_end_only') ? 'history: rows are ended, never edited' : '',
      fns.has('tg_txn_child_guard') ? 'frozen once the transaction is submitted' : '',
      cols.some((c) => c.name === 'status' && c.type === 'finly.lifecycle') ? 'active → inactive → archived' : '',
    ].filter(Boolean).join('; ') || 'see 01 §1.8';

    md += `## \`${t.name}\`\n\n${esc(t.comment)}\n\n**Lifecycle:** ${lifecycle}.\n\n`;
    md +=
      '| Column | Type | Null | Default | Meaning | Sensitivity | Source of truth |\n|---|---|---|---|---|---|---|\n';
    for (const c of cols) {
      const def = c.gen === 's' ? `generated: ${c.def}` : c.def ?? '';
      const meaning = c.comment ?? STANDARD[c.name] ?? (fkOf.has(c.name) ? `→ ${fkOf.get(c.name)}` : '');
      md += `| ${c.name} | ${c.type} | ${c.notnull ? 'no' : 'yes'} | ${esc(def)} | ${esc(meaning)} | ${
        sensitivity(t.name, c.name, c.type)
      } | ${SOURCE_OF_TRUTH[`${t.name}.${c.name}`] ?? ''} |\n`;
    }
    const kind: Record<string, string> = {
      p: 'Primary key',
      f: 'Foreign key',
      u: 'Unique',
      c: 'Check',
      x: 'Exclusion',
    };
    if (cons.length) {
      md += '\n**Keys and constraints**\n\n';
      for (const c of cons) md += `- ${kind[c.type] ?? c.type}: \`${c.def}\`\n`;
    }
    if (idx.length) {
      md += '\n**Indexes**\n\n';
      for (const i of idx) {
        md += `- \`${i.def.replace(/^CREATE (UNIQUE )?INDEX (\S+) ON finly\.\S+ USING /, '$1$2 ')}\`\n`;
      }
    }
    if (pols.length) {
      md += '\n**Row-level security policies**\n\n';
      for (const p of pols) md += `- ${p.name}: ${p.cmd} for ${p.roles.join(', ')}\n`;
    }
    md += '\n';
  }

  await db.close();
  return md;
}

export const DICTIONARY_FILE = OUT;

if (import.meta.main) {
  const md = await renderDictionary();
  await Deno.writeTextFile(OUT, md);
  console.log(`Wrote ${OUT.pathname}`);
}
