// GENERATED by tool/gen_tokens.dart from design-system/project/tokens.json — do not edit by hand.
// ignore_for_file: constant_identifier_names
import 'package:flutter/painting.dart';

/// Colour tokens for one theme (light or dark).
class FyPalette {
  const FyPalette({
    required this.surface,
    required this.surfaceRaised,
    required this.surfaceSunken,
    required this.line,
    required this.lineStrong,
    required this.ink,
    required this.inkMuted,
    required this.brand,
    required this.brandSoft,
    required this.onBrand,
    required this.accent,
    required this.onAccent,
    required this.logoTile,
    required this.logoGlyph,
    required this.logoCoin,
    required this.focus,
    required this.scrim,
    required this.moneyIn,
    required this.moneyInSoft,
    required this.moneyOut,
    required this.moneyOutSoft,
    required this.transfer,
    required this.transferSoft,
    required this.pending,
    required this.pendingSoft,
    required this.blocked,
    required this.blockedSoft,
    required this.reversed,
    required this.reversedSoft,
    required this.outstanding,
    required this.outstandingSoft,
    required this.reconciled,
    required this.reconciledSoft,
    required this.exception,
    required this.exceptionSoft,
    required this.success,
    required this.successSoft,
    required this.error,
    required this.errorSoft,
    required this.warning,
    required this.warningSoft,
    required this.securityStandard,
    required this.securityProtected,
    required this.securityConfidential,
    required this.securityOwner,
  });

  /// Page background behind every screen.
  final Color surface;

  /// Cards, bottom sheets, dialogs, the app bar and the bottom navigation.
  final Color surfaceRaised;

  /// Input fills, keypad keys, inactive segments and skeleton blocks.
  final Color surfaceSunken;

  /// Decorative hairlines between list rows and inside cards. Never the only boundary of a control.
  final Color line;

  /// Input, checkbox and outlined-button borders: at least 3:1 on surface, surface-raised and surface-sunken in both themes.
  final Color lineStrong;

  /// Primary text and icons on surface, surface-raised, surface-sunken, brand-soft and every *-soft status fill.
  final Color ink;

  /// Secondary text (dates, handler, path crumbs, helper text) on surface, surface-raised and surface-sunken.
  final Color inkMuted;

  /// Ledger green. Primary buttons, the add button, active navigation, selected controls and links; as text on surface, surface-raised, surface-sunken and brand-soft.
  final Color brand;

  /// Selected chip and navigation-indicator fill behind ink or brand text.
  final Color brandSoft;

  /// Text and icons on a brand fill (the primary button label, the add button glyph).
  final Color onBrand;

  /// Brass. Non-state highlights only: the cover, onboarding progress, the selected period marker. Never a money direction or a status. 3:1 as a mark on all surfaces.
  final Color accent;

  /// Text on an accent fill.
  final Color onAccent;

  /// The Finly mark tile and the launcher icon background. Identical in both themes: the mark never recolours.
  final Color logoTile;

  /// The F glyph on logo-tile (white, at least 4.5:1).
  final Color logoGlyph;

  /// The brass coin of the mark, on logo-tile (at least 3:1). In the wordmark the dot uses accent instead.
  final Color logoCoin;

  /// Keyboard and switch-access focus ring: 2px gap in the ground colour, then a solid 2px ring. At least 3:1 on every surface.
  final Color focus;

  /// Dim layer behind bottom sheets and dialogs.
  final Color scrim;

  /// Money In / Credit / Avak amounts and the in-arrow glyph, on surface, surface-raised, surface-sunken and money-in-soft. Always with a + sign and the in-arrow.
  final Color moneyIn;

  /// Fill behind the Money In tag.
  final Color moneyInSoft;

  /// Money Out / Debit / Javak amounts and the out-arrow glyph, on surface, surface-raised, surface-sunken and money-out-soft. Always with a minus sign and the out-arrow.
  final Color moneyOut;

  /// Fill behind the Money Out tag.
  final Color moneyOutSoft;

  /// Transfer amounts (same owner, different place) and the swap glyph; no sign. On surface, surface-raised, surface-sunken and transfer-soft.
  final Color transfer;

  /// Fill behind the Transfer tag, and the Draft and Queued badges.
  final Color transferSoft;

  /// Pending approval and Posting text and the clock glyph, on the surfaces and pending-soft.
  final Color pending;

  /// Fill behind the Pending badge and the reserved segment of a fund bar.
  final Color pendingSoft;

  /// Blocked, Rejected, failed and destructive: text, glyph and the danger button, on the surfaces and blocked-soft.
  final Color blocked;

  /// Fill behind the Blocked badge and the conflict block.
  final Color blockedSoft;

  /// Reversed and Corrected: text, the undo glyph and the strike-through on the original amount, on the surfaces and reversed-soft.
  final Color reversed;

  /// Fill behind the Reversed badge.
  final Color reversedSoft;

  /// Outstanding, receivable, payable, advance and reimbursement due: text and the hourglass glyph, on the surfaces and outstanding-soft.
  final Color outstanding;

  /// Fill behind the Outstanding badge and the outstanding segment of a fund bar.
  final Color outstandingSoft;

  /// Posted, Reconciled, Settled and Verified: text and the check glyph, on the surfaces and reconciled-soft. Teal, so it never relies on a red-green split against blocked.
  final Color reconciled;

  /// Fill behind the Posted and Reconciled badges.
  final Color reconciledSoft;

  /// Exception-engine findings and inline warnings (possible duplicate, unusual amount, missing receipt): text and the warning glyph, on the surfaces and exception-soft.
  final Color exception;

  /// Fill behind the Exception badge and warning rows.
  final Color exceptionSoft;

  /// Generic success (saved, verified); an alias of reconciled.
  final Color success;

  /// Fill behind success messages.
  final Color successSoft;

  /// Validation and system errors; an alias of blocked.
  final Color error;

  /// Fill behind error messages.
  final Color errorSoft;

  /// Warnings that need review before saving; an alias of exception.
  final Color warning;

  /// Fill behind warnings.
  final Color warningSoft;

  /// Share and document security level Standard / Internal (no protection).
  final Color securityStandard;

  /// Security level Protected / Secure (password, encryption).
  final Color securityProtected;

  /// Security level Confidential / Restricted (adds watermark, expiry).
  final Color securityConfidential;

  /// Security level Owner Secure / Owner-only / Private (everything mandatory).
  final Color securityOwner;
}

const FyPalette fyLight = FyPalette(
  surface: Color(0xFFF5F6F2),
  surfaceRaised: Color(0xFFFFFFFF),
  surfaceSunken: Color(0xFFEAECE6),
  line: Color(0xFFD7DBD3),
  lineStrong: Color(0xFF737C74),
  ink: Color(0xFF131C17),
  inkMuted: Color(0xFF4B5650),
  brand: Color(0xFF1D5C45),
  brandSoft: Color(0xFFDCEBE3),
  onBrand: Color(0xFFFFFFFF),
  accent: Color(0xFF8A6A1F),
  onAccent: Color(0xFFFFFFFF),
  logoTile: Color(0xFF1D5C45),
  logoGlyph: Color(0xFFFFFFFF),
  logoCoin: Color(0xFFD9B45F),
  focus: Color(0xFF1D5C45),
  scrim: Color(0x8F090E0B),
  moneyIn: Color(0xFF0A5AA8),
  moneyInSoft: Color(0xFFE1EDFA),
  moneyOut: Color(0xFFB23C12),
  moneyOutSoft: Color(0xFFFBE7DE),
  transfer: Color(0xFF4A5763),
  transferSoft: Color(0xFFE6EAEE),
  pending: Color(0xFF7A5300),
  pendingSoft: Color(0xFFF8ECCB),
  blocked: Color(0xFFA1231B),
  blockedSoft: Color(0xFFF9E1DF),
  reversed: Color(0xFF665D55),
  reversedSoft: Color(0xFFEEE9E4),
  outstanding: Color(0xFF74398C),
  outstandingSoft: Color(0xFFF1E4F6),
  reconciled: Color(0xFF00675C),
  reconciledSoft: Color(0xFFDCEFEC),
  exception: Color(0xFFA01858),
  exceptionSoft: Color(0xFFF9E0EB),
  success: Color(0xFF00675C),
  successSoft: Color(0xFFDCEFEC),
  error: Color(0xFFA1231B),
  errorSoft: Color(0xFFF9E1DF),
  warning: Color(0xFFA01858),
  warningSoft: Color(0xFFF9E0EB),
  securityStandard: Color(0xFF4B5650),
  securityProtected: Color(0xFF0A5AA8),
  securityConfidential: Color(0xFF74398C),
  securityOwner: Color(0xFF131C17),
);

const FyPalette fyDark = FyPalette(
  surface: Color(0xFF0E1411),
  surfaceRaised: Color(0xFF161E1A),
  surfaceSunken: Color(0xFF1F2823),
  line: Color(0xFF2C3630),
  lineStrong: Color(0xFF7F8A83),
  ink: Color(0xFFE9EEEA),
  inkMuted: Color(0xFFA8B3AC),
  brand: Color(0xFF7FD1AC),
  brandSoft: Color(0xFF173528),
  onBrand: Color(0xFF0B1712),
  accent: Color(0xFFD9B45F),
  onAccent: Color(0xFF1A1405),
  logoTile: Color(0xFF1D5C45),
  logoGlyph: Color(0xFFFFFFFF),
  logoCoin: Color(0xFFD9B45F),
  focus: Color(0xFF7FD1AC),
  scrim: Color(0xA3000000),
  moneyIn: Color(0xFF8EC5FF),
  moneyInSoft: Color(0xFF0F2A45),
  moneyOut: Color(0xFFFFB08A),
  moneyOutSoft: Color(0xFF42200F),
  transfer: Color(0xFFB9C4CF),
  transferSoft: Color(0xFF232C34),
  pending: Color(0xFFF0C260),
  pendingSoft: Color(0xFF33270A),
  blocked: Color(0xFFFFB3AB),
  blockedSoft: Color(0xFF3F1512),
  reversed: Color(0xFFCDC4BC),
  reversedSoft: Color(0xFF2C2723),
  outstanding: Color(0xFFE2B3F5),
  outstandingSoft: Color(0xFF33193D),
  reconciled: Color(0xFF7FD6C8),
  reconciledSoft: Color(0xFF0F2E2A),
  exception: Color(0xFFFFAFCF),
  exceptionSoft: Color(0xFF3D1226),
  success: Color(0xFF7FD6C8),
  successSoft: Color(0xFF0F2E2A),
  error: Color(0xFFFFB3AB),
  errorSoft: Color(0xFF3F1512),
  warning: Color(0xFFFFAFCF),
  warningSoft: Color(0xFF3D1226),
  securityStandard: Color(0xFFA8B3AC),
  securityProtected: Color(0xFF8EC5FF),
  securityConfidential: Color(0xFFE2B3F5),
  securityOwner: Color(0xFFE9EEEA),
);

/// Spacing, radius and size tokens in logical pixels.
abstract final class FyDims {
  static const double space1 = 4.0;
  static const double space2 = 8.0;
  static const double space3 = 12.0;
  static const double space4 = 16.0;
  static const double space5 = 20.0;
  static const double space6 = 24.0;
  static const double space8 = 32.0;
  static const double space10 = 40.0;
  static const double space12 = 48.0;
  static const double space16 = 64.0;
  static const double radiusXs = 4.0;
  static const double radiusSm = 8.0;
  static const double radiusMd = 12.0;
  static const double radiusLg = 16.0;
  static const double radiusXl = 28.0;
  static const double radiusFull = 9999.0;
  static const double touchMin = 48.0;
  static const double iconMd = 24.0;
  static const double iconSm = 20.0;
  static const double fieldHeight = 56.0;
  static const double keyHeight = 56.0;
  static const double appBar = 64.0;
  static const double navBar = 72.0;
  static const double fab = 56.0;
}

/// Durations (milliseconds) before reduced-motion handling (FyMotion applies it).
abstract final class FyDurations {
  static const Duration durationInstant = Duration(milliseconds: 90);
  static const Duration durationFast = Duration(milliseconds: 150);
  static const Duration durationBase = Duration(milliseconds: 220);
  static const Duration durationSlow = Duration(milliseconds: 320);
}

/// Type scale: font size, line height (both sp) and weight.
class FyTypeStyle {
  const FyTypeStyle(this.size, this.height, this.weight);
  final double size;
  final double height;
  final int weight;
}

abstract final class FyType {
  static const FyTypeStyle display = FyTypeStyle(32.0, 38.0, 700);
  static const FyTypeStyle titleLg = FyTypeStyle(24.0, 30.0, 600);
  static const FyTypeStyle title = FyTypeStyle(20.0, 26.0, 600);
  static const FyTypeStyle section = FyTypeStyle(17.0, 24.0, 600);
  static const FyTypeStyle subhead = FyTypeStyle(15.0, 20.0, 600);
  static const FyTypeStyle body = FyTypeStyle(16.0, 24.0, 400);
  static const FyTypeStyle bodySm = FyTypeStyle(14.0, 20.0, 400);
  static const FyTypeStyle caption = FyTypeStyle(12.0, 16.0, 400);
  static const FyTypeStyle label = FyTypeStyle(13.0, 18.0, 600);
  static const FyTypeStyle button = FyTypeStyle(16.0, 20.0, 600);
  static const FyTypeStyle amountHero = FyTypeStyle(40.0, 46.0, 700);
  static const FyTypeStyle amountLg = FyTypeStyle(28.0, 34.0, 700);
  static const FyTypeStyle amount = FyTypeStyle(18.0, 24.0, 600);
  static const FyTypeStyle amountSm = FyTypeStyle(15.0, 20.0, 600);
  static const FyTypeStyle figure = FyTypeStyle(13.0, 18.0, 500);
  static const double opacityDisabled = 0.38;
  static const double opacityPressed = 0.12;
  static const double opacityHover = 0.08;
}
