-- 0008 seed configuration: permission catalogue, baseline roles, confidentiality levels, configurable lists,
-- entity types, transaction types, posting-rule versions, chart-of-accounts templates and categories, policies.
-- Design: docs/database/03-schema.md; 01-architecture.md §1.12. No people, firms or users: those are bootstrap input
-- (D-011). Everything here is configuration the owner can rename, extend or deactivate later.
-- Data impact: inserts configuration rows only. Recovery: forward fix.

set local role finly_owner;

insert into finly.permission (key, resource_type, action, description, step_up_default) values
  ('admin.full', 'system', 'admin', 'Manage every firm (never anyone''s personal books)', true),
  ('users.manage', 'user', 'manage', 'Create, change, suspend and reset users', true),
  ('access.manage', 'access', 'manage', 'Grant and revoke roles, environment access and access rules', true),
  ('access.break_glass', 'access', 'break_glass', 'Use configured break-glass access', true),
  ('masters.manage', 'master', 'manage', 'Manage firms, people, accounts, locations, categories, types, templates', false),
  ('approvals.manage', 'approval_rule', 'manage', 'Configure approval rules and thresholds', true),
  ('posting_rules.manage', 'posting_rule', 'manage', 'Change posting-rule versions', true),
  ('security.manage', 'security', 'manage', 'Security policies, confidentiality levels, retention', true),
  ('security.emergency', 'security', 'emergency', 'Activate emergency controls', true),
  ('settings.manage', 'setting', 'manage', 'System settings', true),
  ('txn.view', 'txn', 'view', 'See transactions in permitted environments', false),
  ('txn.create', 'txn', 'create', 'Record transactions', false),
  ('txn.submit', 'txn', 'submit', 'Submit transactions for posting or approval', false),
  ('txn.approve', 'txn', 'approve', 'Approve or reject transactions', true),
  ('txn.reverse', 'txn', 'reverse', 'Reverse or correct posted transactions', true),
  ('settlement.create', 'open_item', 'settle', 'Record settlements and set-offs', false),
  ('reconcile.perform', 'reconciliation', 'reconcile', 'Count cash and reconcile accounts', false),
  ('reconcile.approve', 'reconciliation', 'approve', 'Approve reconciliation adjustments', true),
  ('period.close', 'period', 'close', 'Close a month', true),
  ('period.reopen', 'period', 'reopen', 'Reopen a closed month', true),
  ('report.view', 'report', 'view', 'View reports of permitted environments', false),
  ('report.export', 'report', 'export', 'Export reports (separate from viewing)', true),
  ('share.message', 'share', 'message', 'Share a generated message', false),
  ('share.photo', 'share', 'photo', 'Share a generated photo proof', false),
  ('share.pdf', 'share', 'pdf', 'Share a generated PDF', false),
  ('share.secure', 'share', 'secure', 'Share a secure PDF or Secure Viewer link', true),
  ('share.audit', 'share', 'audit', 'See everyone''s share history', false),
  ('attachment.upload', 'attachment', 'upload', 'Attach receipts and documents', false),
  ('attachment.view', 'attachment', 'view', 'Open attachments', false),
  ('audit.view', 'audit', 'view', 'See the audit trail of permitted environments', false),
  ('audit.view_system', 'audit', 'view_system', 'See system-wide audit (users, security, configuration)', false),
  ('exceptions.view_system', 'exception', 'view_system', 'See system-wide exceptions', false),
  ('integrity.view', 'integrity', 'view', 'See Integrity Verifier runs', false);

insert into finly.role (key, name, description, is_system) values
  ('super_admin', 'Super Admin', 'System administration. Never personal-finance visibility (A4).', true),
  ('family_admin', 'Family Admin', 'Runs the permitted firms day to day.', true),
  ('finance_operator', 'Finance / Trusted Operator', 'Records, settles and reconciles; approves within limits.', true),
  ('worker', 'Worker', 'Records entries in assigned places; sees only what is assigned (L13).', true),
  ('read_only', 'Read Only', 'Views permitted environments.', true),
  ('partner', 'Partner', 'Views permitted reports and updates.', true),
  ('auditor', 'Auditor', 'Reviews books, audit trail and integrity runs.', true);

insert into finly.role_permission (role_id, permission_id)
select r.id, p.id
from finly.role r
join finly.permission p on p.key = any (case r.key
  when 'super_admin' then array['admin.full', 'users.manage', 'access.manage', 'masters.manage', 'approvals.manage',
    'posting_rules.manage', 'security.manage', 'security.emergency', 'settings.manage', 'audit.view',
    'audit.view_system', 'exceptions.view_system', 'integrity.view', 'share.audit', 'txn.view', 'report.view']
  when 'family_admin' then array['masters.manage', 'txn.view', 'txn.create', 'txn.submit', 'txn.approve', 'txn.reverse',
    'settlement.create', 'reconcile.perform', 'reconcile.approve', 'period.close', 'report.view', 'report.export',
    'share.message', 'share.photo', 'share.pdf', 'share.secure', 'attachment.upload', 'attachment.view', 'audit.view']
  when 'finance_operator' then array['txn.view', 'txn.create', 'txn.submit', 'txn.approve', 'settlement.create',
    'reconcile.perform', 'report.view', 'share.message', 'share.photo', 'share.pdf', 'attachment.upload',
    'attachment.view']
  when 'worker' then array['txn.create', 'txn.submit', 'attachment.upload']
  when 'read_only' then array['txn.view', 'report.view', 'attachment.view']
  when 'partner' then array['txn.view', 'report.view']
  when 'auditor' then array['txn.view', 'report.view', 'report.export', 'attachment.view', 'audit.view',
    'integrity.view']
end);

insert into finly.confidentiality_level (key, label, rank, description) values
  ('public', 'Public (within Finly)', 10, 'Anyone signed in who may enter the environment'),
  ('internal', 'Internal', 20, 'Members of the environment'),
  ('company_only', 'Company only', 30, 'The firm''s own people'),
  ('family_only', 'Family only', 40, 'Family members with access'),
  ('restricted', 'Restricted', 50, 'Named people only'),
  ('confidential', 'Confidential', 60, 'Named people; sharing protected by default'),
  ('highly_confidential', 'Highly confidential', 70, 'Named people; secure sharing mandatory'),
  ('owner_only', 'Owner only', 80, 'Owners of the firm, or the person, only'),
  ('private', 'Private', 90, 'The owner alone'),
  ('secret', 'Secret', 100, 'The owner alone; not discoverable');

insert into finly.lookup_value (list_key, key, label, sort_order) values
  ('location_type', 'vault', 'Tijori / vault', 10), ('location_type', 'drawer', 'Drawer', 20),
  ('location_type', 'locker', 'Locker', 30), ('location_type', 'wardrobe', 'Wardrobe', 40),
  ('location_type', 'hand_cash', 'Cash in hand', 50), ('location_type', 'office_cash', 'Office cash', 60),
  ('location_type', 'bank_current', 'Bank — current account', 70), ('location_type', 'bank_savings', 'Bank — savings account', 80),
  ('location_type', 'wallet', 'Wallet', 90), ('location_type', 'upi', 'UPI', 100), ('location_type', 'other', 'Other', 990),
  ('payment_method', 'cash', 'Cash', 10), ('payment_method', 'bank', 'Bank transfer', 20), ('payment_method', 'upi', 'UPI', 30),
  ('payment_method', 'card', 'Card', 40), ('payment_method', 'cheque', 'Cheque', 50), ('payment_method', 'wallet', 'Wallet', 60),
  ('payment_method', 'other', 'Other', 990),
  ('fund_kind', 'operating', 'Operating', 10), ('fund_kind', 'owner', 'Owner', 20), ('fund_kind', 'reserve', 'Reserve', 30),
  ('fund_kind', 'travel', 'Travel', 40), ('fund_kind', 'emergency', 'Emergency', 50), ('fund_kind', 'project', 'Project', 60),
  ('fund_kind', 'restricted', 'Restricted', 70), ('fund_kind', 'private', 'Private', 80), ('fund_kind', 'general', 'General', 5),
  ('event_kind', 'trip', 'Trip', 10), ('event_kind', 'firm_visit', 'Firm visit', 20),
  ('event_kind', 'angadiya_visit', 'Angadiya visit', 30), ('event_kind', 'customer_visit', 'Customer visit', 40),
  ('event_kind', 'supplier_visit', 'Supplier visit', 50), ('event_kind', 'exhibition', 'Exhibition', 60),
  ('event_kind', 'purchase_trip', 'Purchase trip', 70), ('event_kind', 'project', 'Project', 80),
  ('event_kind', 'family_event', 'Family event', 90), ('event_kind', 'meeting', 'Meeting', 100),
  ('event_kind', 'other', 'Other', 990),
  ('document_kind', 'receipt', 'Receipt', 10), ('document_kind', 'bill', 'Bill', 20), ('document_kind', 'invoice', 'Invoice', 30),
  ('document_kind', 'payment_proof', 'Payment proof', 40), ('document_kind', 'bank_statement', 'Bank statement', 50),
  ('document_kind', 'cheque_image', 'Cheque image', 60), ('document_kind', 'tax_document', 'Tax document', 70),
  ('document_kind', 'credit_note', 'Credit note', 80), ('document_kind', 'debit_note', 'Debit note', 90),
  ('document_kind', 'photo', 'Photo', 100), ('document_kind', 'other', 'Other', 990),
  ('worker_type', 'worker', 'Worker', 10), ('worker_type', 'employee', 'Employee', 20), ('worker_type', 'driver', 'Driver', 30),
  ('worker_type', 'accountant', 'Accountant', 40), ('worker_type', 'other', 'Other', 990),
  ('relation_label', 'owner', 'Owner', 10), ('relation_label', 'partner', 'Partner', 20),
  ('relation_label', 'worker', 'Worker', 30), ('relation_label', 'employee', 'Employee', 40),
  ('relation_label', 'family', 'Family', 50), ('relation_label', 'other', 'Other', 990);

insert into finly.entity_type (kind, key, label) values
  ('firm', 'company', 'Company'), ('firm', 'partnership', 'Partnership'), ('firm', 'proprietorship', 'Proprietorship'),
  ('person', 'individual', 'Individual'), ('pool', 'family_pool', 'Family pool'),
  ('party', 'customer', 'Customer'), ('party', 'supplier', 'Supplier'), ('party', 'agent', 'Agent'),
  ('party', 'angadiya', 'Angadiya'), ('party', 'bank', 'Bank'), ('party', 'other_party', 'Other business or person');

insert into finly.txn_type (key, label, intent_type, sort_order) values
  ('transfer', 'Transfer / handover', 'transfer', 10),
  ('transit_confirm', 'Confirm handover received', 'transit_confirm', 15),
  ('expense', 'Expense', 'expense', 20),
  ('bill', 'Bill (unpaid)', 'bill', 25),
  ('nonowner_payment', 'Money given to a non-owner', 'nonowner_payment', 30),
  ('income', 'Income', 'income', 40),
  ('unidentified_receipt', 'Unidentified money received', 'unidentified_receipt', 45),
  ('advance_give', 'Give an advance', 'advance_give', 50),
  ('advance_account', 'Account for an advance', 'advance_account', 55),
  ('loan', 'Loan', 'loan', 60),
  ('loan_repayment', 'Loan repayment', 'loan_repayment', 65),
  ('capital_contribution', 'Capital put in', 'capital_contribution', 70),
  ('withdrawal', 'Owner withdrawal', 'withdrawal', 75),
  ('interentity_transfer', 'Transfer between firms or people', 'interentity_transfer', 80),
  ('settlement', 'Settle what is owed', 'settlement', 85),
  ('offset', 'Set off amounts owed both ways', 'offset', 90),
  ('opening_balance', 'Opening balance', 'opening_balance', 95),
  ('cash_adjustment', 'Cash difference (approved)', 'cash_adjustment', 100),
  ('reversal', 'Reversal', 'reversal', 900),
  ('correction', 'Correction', 'correction', 910);

insert into finly.posting_rule_version (intent_type, rule_version, engine_version, definition)
select t.intent_type, 1, '0.1.0',
  jsonb_build_object('planner', 'backend/src/domain/engine/plan.ts', 'spec', 'docs/ACCOUNTING-ENGINE.md §5')
from finly.txn_type t where t.intent_type not in ('reversal', 'correction');

insert into finly.retention_policy (data_class, retain_days, action, description) values
  ('financial_records', 3285, 'archive', 'Books of account: 8 years after the financial year (Companies Act s.128(5)); never deleted automatically — open question Q8'),
  ('audit_log', 3285, 'archive', 'Kept with the books they explain'),
  ('security_events', 730, 'delete', '2 years'),
  ('sessions', 90, 'delete', '90 days after expiry or revocation'),
  ('idempotency', 30, 'delete', '30 days'),
  ('notifications', 365, 'delete', '1 year'),
  ('secure_link_access', 730, 'delete', '2 years'),
  ('generated_documents', 365, 'delete', 'The generated file; the record of the share stays');

insert into finly.emergency_control (control_key) values
  ('freeze_financial_writes'), ('disable_exports'), ('disable_sharing'), ('require_reauth');

insert into finly.key_version (purpose, version, algorithm, status, activated_at) values
  ('data', 1, 'AES-256-GCM, key = HKDF-SHA-256(KEK v1, "finly/data/v1")', 'active', now()),
  ('blind_index', 1, 'HMAC-SHA-256 truncated to 16 bytes, key = HKDF(KEK v1, "finly/blind_index/v1")', 'active', now()),
  ('hash_chain', 1, 'HMAC-SHA-256, key = HKDF(KEK v1, "finly/hash_chain/v1")', 'active', now()),
  ('file', 1, 'AES-256-GCM per file, key = HKDF(KEK v1, "finly/file/v1" || file id)', 'active', now()),
  ('mpin_pepper', 1, 'HMAC-SHA-256 pepper before Argon2id, key = HKDF(KEK v1, "finly/mpin_pepper/v1")', 'active', now());

insert into finly.system_setting (key, value, description) values
  ('handover_confirmation_default', 'false', 'Receiver confirmation of handovers, OFF by default (owner, F2)'),
  ('backdating_limit_days', '31', 'How far back an entry may be dated without extra permission (AC8)'),
  ('max_attachment_bytes', '26214400', 'Largest attachment accepted (25 MB)'),
  ('session_idle_minutes', '43200', 'A remembered session expires after 30 days without use'),
  ('session_absolute_days', '90', 'A remembered session always ends after 90 days (N3)'),
  ('auto_lock_seconds', '60', 'App locks this long after going to the background (N11)'),
  ('access_token_minutes', '10', 'Lifetime of an access token');

insert into finly.security_policy (control_key, scope_type, mode, user_may_change, value) values
  ('password_protection', 'system', 'default_on', true, '{}'),
  ('encryption', 'system', 'default_on', true, '{}'),
  ('watermark', 'system', 'default_on', true, '{}'),
  ('expiry', 'system', 'default_on', true, '{"hours": 24}'),
  ('secure_viewer', 'system', 'off', true, '{}'),
  ('revocable_access', 'system', 'default_on', true, '{}'),
  ('recipient_marking', 'system', 'default_on', true, '{}'),
  ('download_allowed', 'system', 'default_on', true, '{}'),
  ('print_allowed', 'system', 'off', true, '{}'),
  ('require_user_verification', 'system', 'mandatory', false, '{}'),
  ('require_step_up', 'system', 'default_on', true, '{}'),
  ('mpin_required', 'system', 'off', true, '{}');
-- MFA is mandatory for the Super Admin role (N13).
insert into finly.security_policy (control_key, scope_type, scope_id, mode, user_may_change, value)
select 'mfa_required', 'role', id, 'mandatory', false, '{}' from finly.role where key = 'super_admin';

insert into finly.coa_template_account
  (entity_kind, code, name, class, role, requires_location, requires_counterparty, requires_category, sort_order) values
  ('firm', '1100', 'Cash', 'asset', 'cash', true, false, false, 10),
  ('person', '1100', 'Cash', 'asset', 'cash', true, false, false, 20),
  ('pool', '1100', 'Cash', 'asset', 'cash', true, false, false, 30),
  ('firm', '1200', 'Bank', 'asset', 'bank', true, false, false, 40),
  ('person', '1200', 'Bank', 'asset', 'bank', true, false, false, 50),
  ('pool', '1200', 'Bank', 'asset', 'bank', true, false, false, 60),
  ('firm', '1250', 'Wallet / UPI balance', 'asset', 'wallet', true, false, false, 70),
  ('person', '1250', 'Wallet / UPI balance', 'asset', 'wallet', true, false, false, 80),
  ('pool', '1250', 'Wallet / UPI balance', 'asset', 'wallet', true, false, false, 90),
  ('firm', '1300', 'Inter-entity receivable', 'asset', 'interentity_receivable', false, true, false, 100),
  ('person', '1300', 'Inter-entity receivable', 'asset', 'interentity_receivable', false, true, false, 110),
  ('pool', '1300', 'Inter-entity receivable', 'asset', 'interentity_receivable', false, true, false, 120),
  ('firm', '1310', 'Advances given', 'asset', 'advances_given', false, true, false, 130),
  ('person', '1310', 'Advances given', 'asset', 'advances_given', false, true, false, 140),
  ('pool', '1310', 'Advances given', 'asset', 'advances_given', false, true, false, 150),
  ('firm', '1320', 'Loans given', 'asset', 'loans_given', false, true, false, 160),
  ('person', '1320', 'Loans given', 'asset', 'loans_given', false, true, false, 170),
  ('pool', '1320', 'Loans given', 'asset', 'loans_given', false, true, false, 180),
  ('firm', '1330', 'Customer receivable', 'asset', 'customer_receivable', false, true, false, 190),
  ('person', '1330', 'Customer receivable', 'asset', 'customer_receivable', false, true, false, 200),
  ('pool', '1330', 'Customer receivable', 'asset', 'customer_receivable', false, true, false, 210),
  ('person', '1340', 'Investment in firms', 'asset', 'investment_in_firms', false, true, false, 220),
  ('pool', '1340', 'Investment in firms', 'asset', 'investment_in_firms', false, true, false, 230),
  ('firm', '1390', 'Cash in transit', 'asset', 'cash_in_transit', false, false, false, 240),
  ('person', '1390', 'Cash in transit', 'asset', 'cash_in_transit', false, false, false, 250),
  ('pool', '1390', 'Cash in transit', 'asset', 'cash_in_transit', false, false, false, 260),
  ('firm', '1900', 'Suspense (unidentified money)', 'asset', 'suspense', false, false, false, 270),
  ('person', '1900', 'Suspense (unidentified money)', 'asset', 'suspense', false, false, false, 280),
  ('pool', '1900', 'Suspense (unidentified money)', 'asset', 'suspense', false, false, false, 290),
  ('firm', '2100', 'Inter-entity payable', 'liability', 'interentity_payable', false, true, false, 300),
  ('person', '2100', 'Inter-entity payable', 'liability', 'interentity_payable', false, true, false, 310),
  ('pool', '2100', 'Inter-entity payable', 'liability', 'interentity_payable', false, true, false, 320),
  ('firm', '2110', 'Supplier payable', 'liability', 'supplier_payable', false, true, false, 330),
  ('person', '2110', 'Supplier payable', 'liability', 'supplier_payable', false, true, false, 340),
  ('pool', '2110', 'Supplier payable', 'liability', 'supplier_payable', false, true, false, 350),
  ('firm', '2120', 'Loans taken', 'liability', 'loans_taken', false, true, false, 360),
  ('person', '2120', 'Loans taken', 'liability', 'loans_taken', false, true, false, 370),
  ('pool', '2120', 'Loans taken', 'liability', 'loans_taken', false, true, false, 380),
  ('firm', '2130', 'Advances received', 'liability', 'advances_received', false, true, false, 390),
  ('person', '2130', 'Advances received', 'liability', 'advances_received', false, true, false, 400),
  ('pool', '2130', 'Advances received', 'liability', 'advances_received', false, true, false, 410),
  ('firm', '3100', 'Owner capital', 'equity', 'owner_capital', false, true, false, 420),
  ('firm', '3150', 'Owner drawings', 'drawings', 'owner_drawings', false, true, false, 430),
  ('firm', '3200', 'Opening balance equity', 'equity', 'opening_balance_equity', false, false, false, 440),
  ('person', '3200', 'Opening balance equity', 'equity', 'opening_balance_equity', false, false, false, 450),
  ('pool', '3200', 'Opening balance equity', 'equity', 'opening_balance_equity', false, false, false, 460),
  ('firm', '3300', 'Retained earnings', 'equity', 'retained_earnings', false, false, false, 470),
  ('person', '3300', 'Retained earnings', 'equity', 'retained_earnings', false, false, false, 480),
  ('pool', '3300', 'Retained earnings', 'equity', 'retained_earnings', false, false, false, 490),
  ('firm', '4100', 'Sales', 'revenue', 'revenue', false, false, true, 500),
  ('person', '4100', 'Sales', 'revenue', 'revenue', false, false, true, 510),
  ('pool', '4100', 'Sales', 'revenue', 'revenue', false, false, true, 520),
  ('firm', '4200', 'Service income', 'revenue', 'revenue', false, false, true, 530),
  ('person', '4200', 'Service income', 'revenue', 'revenue', false, false, true, 540),
  ('pool', '4200', 'Service income', 'revenue', 'revenue', false, false, true, 550),
  ('firm', '4300', 'Commission and brokerage', 'revenue', 'revenue', false, false, true, 560),
  ('person', '4300', 'Commission and brokerage', 'revenue', 'revenue', false, false, true, 570),
  ('pool', '4300', 'Commission and brokerage', 'revenue', 'revenue', false, false, true, 580),
  ('firm', '4400', 'Interest income', 'revenue', 'revenue', false, false, true, 590),
  ('person', '4400', 'Interest income', 'revenue', 'revenue', false, false, true, 600),
  ('pool', '4400', 'Interest income', 'revenue', 'revenue', false, false, true, 610),
  ('firm', '4500', 'Rental income', 'revenue', 'revenue', false, false, true, 620),
  ('person', '4500', 'Rental income', 'revenue', 'revenue', false, false, true, 630),
  ('pool', '4500', 'Rental income', 'revenue', 'revenue', false, false, true, 640),
  ('person', '4600', 'Salary income', 'revenue', 'revenue', false, false, true, 650),
  ('pool', '4600', 'Salary income', 'revenue', 'revenue', false, false, true, 660),
  ('firm', '4900', 'Other income', 'revenue', 'revenue', false, false, true, 670),
  ('person', '4900', 'Other income', 'revenue', 'revenue', false, false, true, 680),
  ('pool', '4900', 'Other income', 'revenue', 'revenue', false, false, true, 690),
  ('firm', '5100', 'Travel and conveyance', 'expense', 'expense', false, false, true, 700),
  ('person', '5100', 'Travel and conveyance', 'expense', 'expense', false, false, true, 710),
  ('pool', '5100', 'Travel and conveyance', 'expense', 'expense', false, false, true, 720),
  ('firm', '5150', 'Hotel and lodging', 'expense', 'expense', false, false, true, 730),
  ('person', '5150', 'Hotel and lodging', 'expense', 'expense', false, false, true, 740),
  ('pool', '5150', 'Hotel and lodging', 'expense', 'expense', false, false, true, 750),
  ('firm', '5200', 'Food and refreshments', 'expense', 'expense', false, false, true, 760),
  ('person', '5200', 'Food and refreshments', 'expense', 'expense', false, false, true, 770),
  ('pool', '5200', 'Food and refreshments', 'expense', 'expense', false, false, true, 780),
  ('firm', '5250', 'Fuel', 'expense', 'expense', false, false, true, 790),
  ('person', '5250', 'Fuel', 'expense', 'expense', false, false, true, 800),
  ('pool', '5250', 'Fuel', 'expense', 'expense', false, false, true, 810),
  ('firm', '5300', 'Salary and wages', 'expense', 'expense', false, false, true, 820),
  ('person', '5300', 'Salary and wages', 'expense', 'expense', false, false, true, 830),
  ('pool', '5300', 'Salary and wages', 'expense', 'expense', false, false, true, 840),
  ('firm', '5350', 'Rent', 'expense', 'expense', false, false, true, 850),
  ('person', '5350', 'Rent', 'expense', 'expense', false, false, true, 860),
  ('pool', '5350', 'Rent', 'expense', 'expense', false, false, true, 870),
  ('firm', '5400', 'Utilities', 'expense', 'expense', false, false, true, 880),
  ('person', '5400', 'Utilities', 'expense', 'expense', false, false, true, 890),
  ('pool', '5400', 'Utilities', 'expense', 'expense', false, false, true, 900),
  ('firm', '5450', 'Professional fees', 'expense', 'expense', false, false, true, 910),
  ('person', '5450', 'Professional fees', 'expense', 'expense', false, false, true, 920),
  ('pool', '5450', 'Professional fees', 'expense', 'expense', false, false, true, 930),
  ('firm', '5500', 'Repairs and maintenance', 'expense', 'expense', false, false, true, 940),
  ('person', '5500', 'Repairs and maintenance', 'expense', 'expense', false, false, true, 950),
  ('pool', '5500', 'Repairs and maintenance', 'expense', 'expense', false, false, true, 960),
  ('firm', '5550', 'Bank charges', 'expense', 'expense', false, false, true, 970),
  ('person', '5550', 'Bank charges', 'expense', 'expense', false, false, true, 980),
  ('pool', '5550', 'Bank charges', 'expense', 'expense', false, false, true, 990),
  ('firm', '5600', 'Marketing', 'expense', 'expense', false, false, true, 1000),
  ('person', '5600', 'Marketing', 'expense', 'expense', false, false, true, 1010),
  ('pool', '5600', 'Marketing', 'expense', 'expense', false, false, true, 1020),
  ('firm', '5650', 'Firm charges and commission paid', 'expense', 'expense', false, false, true, 1030),
  ('person', '5650', 'Firm charges and commission paid', 'expense', 'expense', false, false, true, 1040),
  ('pool', '5650', 'Firm charges and commission paid', 'expense', 'expense', false, false, true, 1050),
  ('firm', '5700', 'Courier and transport', 'expense', 'expense', false, false, true, 1060),
  ('person', '5700', 'Courier and transport', 'expense', 'expense', false, false, true, 1070),
  ('pool', '5700', 'Courier and transport', 'expense', 'expense', false, false, true, 1080),
  ('firm', '5800', 'Interest expense', 'expense', 'expense', false, false, true, 1090),
  ('person', '5800', 'Interest expense', 'expense', 'expense', false, false, true, 1100),
  ('pool', '5800', 'Interest expense', 'expense', 'expense', false, false, true, 1110),
  ('firm', '5890', 'Other expenses', 'expense', 'expense', false, false, true, 1120),
  ('person', '5890', 'Other expenses', 'expense', 'expense', false, false, true, 1130),
  ('pool', '5890', 'Other expenses', 'expense', 'expense', false, false, true, 1140),
  ('firm', '5900', 'Cash over / short', 'expense', 'expense', false, false, true, 1150),
  ('person', '5900', 'Cash over / short', 'expense', 'expense', false, false, true, 1160),
  ('pool', '5900', 'Cash over / short', 'expense', 'expense', false, false, true, 1170),
  ('firm', '5950', 'Bad debts and write-offs', 'expense', 'expense', false, false, true, 1180),
  ('person', '5950', 'Bad debts and write-offs', 'expense', 'expense', false, false, true, 1190),
  ('pool', '5950', 'Bad debts and write-offs', 'expense', 'expense', false, false, true, 1200);

insert into finly.category (kind, key, name, account_code, sort_order) values
  ('expense', 'travel', 'Travel', '5100', 10),
  ('expense', 'local_transport', 'Local transport', '5100', 20),
  ('expense', 'hotel', 'Hotel', '5150', 30),
  ('expense', 'food', 'Food', '5200', 40),
  ('expense', 'petrol', 'Petrol', '5250', 50),
  ('expense', 'salary', 'Salary', '5300', 60),
  ('expense', 'labour', 'Labour', '5300', 70),
  ('expense', 'rent', 'Rent', '5350', 80),
  ('expense', 'electricity', 'Electricity', '5400', 90),
  ('expense', 'internet', 'Internet', '5400', 100),
  ('expense', 'professional_fees', 'Professional fees', '5450', 110),
  ('expense', 'repairs', 'Repairs', '5500', 120),
  ('expense', 'bank_charges', 'Bank charges', '5550', 130),
  ('expense', 'marketing', 'Marketing', '5600', 140),
  ('expense', 'firm_charges', 'Firm charges', '5650', 150),
  ('expense', 'courier', 'Courier', '5700', 160),
  ('expense', 'other_expense', 'Other expense', '5890', 170),
  ('expense', 'interest_paid', 'Interest paid', '5800', 180),
  ('expense', 'cash_difference', 'Cash difference', '5900', 190),
  ('expense', 'bad_debt', 'Bad debt', '5950', 200),
  ('income', 'sales', 'Sales', '4100', 210),
  ('income', 'service', 'Service income', '4200', 220),
  ('income', 'commission', 'Commission', '4300', 230),
  ('income', 'interest', 'Interest', '4400', 240),
  ('income', 'rent_received', 'Rent received', '4500', 250),
  ('income', 'salary_received', 'Salary received', '4600', 260),
  ('income', 'other_income', 'Other income', '4900', 270);
