/**
 * Reads the import graph of backend/src and checks it against arch/rules.ts: no import cycles between files, no layer
 * importing what it may not, no source file importing tests or tools. Also renders the module map.
 */
import { type Layer, layerOf, LAYERS } from './rules.ts';

const ROOT = new URL('../', import.meta.url);
const IMPORT = /(?:^|\n)\s*(?:import|export)\s[^'"]*?from\s*['"]([^'"]+)['"]|import\(\s*['"]([^'"]+)['"]\s*\)/g;

export interface Graph {
  /** File (relative to backend/) → its imports: relative files resolved, bare specifiers as written. */
  edges: Map<string, string[]>;
}

async function* walk(dir: URL, rel: string): AsyncGenerator<string> {
  for await (const e of Deno.readDir(dir)) {
    if (e.isDirectory) yield* walk(new URL(`${e.name}/`, dir), `${rel}${e.name}/`);
    else if (e.name.endsWith('.ts')) yield `${rel}${e.name}`;
  }
}

function resolve(from: string, spec: string): string {
  if (!spec.startsWith('.')) return spec;
  const parts = from.split('/').slice(0, -1);
  for (const p of spec.split('/')) {
    if (p === '..') parts.pop();
    else if (p !== '.') parts.push(p);
  }
  return parts.join('/');
}

export async function readGraph(): Promise<Graph> {
  const edges = new Map<string, string[]>();
  for await (const file of walk(new URL('src/', ROOT), 'src/')) {
    const text = await Deno.readTextFile(new URL(file, ROOT));
    const specs = [...text.matchAll(IMPORT)].map((m) => m[1] ?? m[2]);
    edges.set(file, [...new Set(specs.map((s) => resolve(file, s)))].sort());
  }
  return { edges: new Map([...edges].sort(([a], [b]) => a.localeCompare(b))) };
}

/** Every cycle found by depth-first search, each as the list of files around it. */
export function cycles(g: Graph): string[][] {
  const found: string[][] = [];
  const state = new Map<string, 'open' | 'done'>();
  const stack: string[] = [];
  const visit = (f: string) => {
    state.set(f, 'open');
    stack.push(f);
    for (const t of g.edges.get(f) ?? []) {
      if (!g.edges.has(t)) continue;
      if (state.get(t) === 'open') found.push([...stack.slice(stack.indexOf(t)), t]);
      else if (!state.has(t)) visit(t);
    }
    stack.pop();
    state.set(f, 'done');
  };
  for (const f of g.edges.keys()) if (!state.has(f)) visit(f);
  return found;
}

/** Imports that break a layer rule, as "from → to (why)". */
export function violations(g: Graph): string[] {
  const out: string[] = [];
  for (const [from, targets] of g.edges) {
    const layer = layerOf(from);
    if (!layer) {
      out.push(`${from} is in no layer (add it to arch/rules.ts)`);
      continue;
    }
    for (const to of targets) {
      const why = refusal(layer, to);
      if (why) out.push(`${from} → ${to} (${why})`);
    }
  }
  return out;
}

function refusal(layer: Layer, to: string): string | undefined {
  if (to.startsWith('src/')) {
    if (to.startsWith(layer.path)) return undefined;
    return layer.may.some((p) => to.startsWith(p)) ? undefined : `${layer.name} may not import ${layerOf(to)?.name}`;
  }
  if (to.startsWith('tests/') || to.startsWith('db/') || to.startsWith('arch/') || to.startsWith('bench/')) {
    return 'source never imports tests or tools';
  }
  return layer.external.includes(to) ? undefined : `${layer.name} may not use the package ${to}`;
}

/** Markdown page with the layer table and a Mermaid graph of the layers actually imported today. */
export function renderMap(g: Graph): string {
  const used = new Map<string, Set<string>>();
  for (const [from, targets] of g.edges) {
    const a = layerOf(from)?.name ?? '?';
    for (const to of targets) {
      const b = to.startsWith('src/') ? layerOf(to)?.name : undefined;
      if (b && b !== a) (used.get(a) ?? used.set(a, new Set()).get(a)!).add(b);
    }
  }
  const files = (l: Layer) => [...g.edges.keys()].filter((f) => f.startsWith(l.path)).length;
  const lines = [
    '# Backend module map',
    '',
    'Generated by `deno task arch:map` from [backend/arch/rules.ts](../../backend/arch/rules.ts) and the actual',
    'imports in `backend/src`. Do not edit by hand: `tests/architecture/boundaries_test.ts` fails when this page is out',
    'of date, when any import cycle appears, or when a layer imports what its rule does not allow (add-on 15 §2.2).',
    '',
    '| Layer | Path | Files | Purpose | May import | Packages |',
    '|---|---|---|---|---|---|',
    ...LAYERS.map((l) =>
      `| ${l.name} | \`${l.path}\` | ${files(l)} | ${l.purpose} | ${l.may.map((m) => `\`${m}\``).join(', ') || '—'} | ${
        l.external.map((e) => `\`${e}\``).join(', ') || '—'
      } |`
    ),
    '',
    '## Dependencies in use',
    '',
    '```mermaid',
    'flowchart LR',
    ...LAYERS.filter((l) => files(l) > 0).map((l) => `  ${l.name}[${l.name}]`),
    ...[...used].flatMap(([a, bs]) => [...bs].sort().map((b) => `  ${a} --> ${b}`)),
    '```',
    '',
    'Layers with no files yet are planned and already constrained by their rule.',
    '',
  ];
  return lines.join('\n');
}
