// Generates lib/core/design_system/tokens.g.dart from design-system/project/tokens.json (the single theme source,
// design-system/project/06-flutter-implementation.md). Run from app/: dart run tool/gen_tokens.dart
// The output is committed; a test fails when it no longer matches tokens.json.
import 'dart:convert';
import 'dart:io';

String camel(String name) {
  final parts = name.split('-');
  return parts.first +
      parts.skip(1).map((p) => p[0].toUpperCase() + p.substring(1)).join();
}

String color(String value) {
  final rgba = RegExp(r'^rgba\((\d+),\s*(\d+),\s*(\d+),\s*([0-9.]+)\)$')
      .firstMatch(value);
  if (rgba != null) {
    final hex = [1, 2, 3]
        .map((i) => int.parse(rgba.group(i)!).toRadixString(16).padLeft(2, '0'))
        .join();
    final alpha = (double.parse(rgba.group(4)!) * 255)
        .round()
        .toRadixString(16)
        .padLeft(2, '0');
    return 'Color(0x${alpha.toUpperCase()}${hex.toUpperCase()})';
  }
  final h = value.replaceFirst('#', '');
  if (h.length != 6) throw FormatException('Unexpected colour $value');
  return 'Color(0xFF${h.toUpperCase()})';
}

/// A colour's value in one theme, following `{other-token}` references.
String resolve(
  List<Map<String, dynamic>> colors,
  Map<String, dynamic> token,
  String theme, [
  int depth = 0,
]) {
  if (depth > 8) throw FormatException('Reference loop at ${token['name']}');
  final value = token['value'];
  final raw = value is Map ? value[theme] as String : value as String;
  final ref = RegExp(r'^\{([a-z0-9-]+)\}$').firstMatch(raw);
  if (ref == null) return raw;
  final target = colors.firstWhere(
    (c) => c['name'] == ref.group(1),
    orElse: () => throw FormatException('No token $raw'),
  );
  return resolve(colors, target, theme, depth + 1);
}

double px(String v) =>
    double.parse(v.replaceAll('px', '').replaceAll('ms', ''));

String generate(Map<String, dynamic> t) {
  final colors = (t['color']['tokens'] as List).cast<Map<String, dynamic>>();
  final b = StringBuffer()
    ..writeln(
      '// GENERATED by tool/gen_tokens.dart from design-system/project/tokens.json — do not edit by hand.',
    )
    ..writeln('// ignore_for_file: constant_identifier_names')
    ..writeln("import 'package:flutter/painting.dart';")
    ..writeln()
    ..writeln('/// Colour tokens for one theme (light or dark).')
    ..writeln('class FyPalette {')
    ..writeln('  const FyPalette({');
  for (final c in colors) {
    b.writeln('    required this.${camel(c['name'] as String)},');
  }
  b.writeln('  });');
  for (final c in colors) {
    b
      ..writeln('  /// ${(c['usage'] as String).replaceAll('\n', ' ')}')
      ..writeln('  final Color ${camel(c['name'] as String)};');
  }
  b.writeln('}');
  for (final theme in ['light', 'dark']) {
    b
      ..writeln()
      ..writeln(
        'const FyPalette fy${theme[0].toUpperCase()}${theme.substring(1)} = FyPalette(',
      );
    for (final c in colors) {
      b.writeln(
        '  ${camel(c['name'] as String)}: ${color(resolve(colors, c, theme))},',
      );
    }
    b.writeln(');');
  }
  b
    ..writeln()
    ..writeln('/// Spacing, radius and size tokens in logical pixels.')
    ..writeln('abstract final class FyDims {');
  for (final group in ['spacing', 'radius', 'size']) {
    for (final s in (t[group]['tokens'] as List).cast<Map<String, dynamic>>()) {
      b.writeln(
        '  static const double ${camel(s['name'] as String)} = ${px(s['value'] as String)};',
      );
    }
  }
  b
    ..writeln('}')
    ..writeln()
    ..writeln(
      '/// Durations (milliseconds) before reduced-motion handling (FyMotion applies it).',
    )
    ..writeln('abstract final class FyDurations {');
  for (final d
      in (t['duration']['tokens'] as List).cast<Map<String, dynamic>>()) {
    b.writeln(
      '  static const Duration ${camel(d['name'] as String)} = Duration(milliseconds: ${px(d['value'] as String).round()});',
    );
  }
  b
    ..writeln('}')
    ..writeln()
    ..writeln('/// Type scale: font size, line height (both sp) and weight.')
    ..writeln('class FyTypeStyle {')
    ..writeln('  const FyTypeStyle(this.size, this.height, this.weight);')
    ..writeln('  final double size;')
    ..writeln('  final double height;')
    ..writeln('  final int weight;')
    ..writeln('}')
    ..writeln()
    ..writeln('abstract final class FyType {');
  for (final g in (t['type']['groups'] as List).cast<Map<String, dynamic>>()) {
    for (final s in (g['styles'] as List).cast<Map<String, dynamic>>()) {
      b.writeln(
        '  static const FyTypeStyle ${camel(s['name'] as String)} = '
        'FyTypeStyle(${px(s['fontSize'] as String)}, ${px(s['lineHeight'] as String)}, ${s['fontWeight']});',
      );
    }
  }
  for (final o
      in (t['opacity']['tokens'] as List).cast<Map<String, dynamic>>()) {
    b.writeln(
      '  static const double ${camel(o['name'] as String)} = ${o['value']};',
    );
  }
  b.writeln('}');
  return b.toString();
}

/// The generated source exactly as `dart format` writes it, so the committed file and the check agree.
String formatted(String source) {
  final dir = Directory.systemTemp.createTempSync('fy_tokens');
  try {
    final tmp = File('${dir.path}/tokens.g.dart')..writeAsStringSync(source);
    final r = Process.runSync(Platform.resolvedExecutable, [
      'format',
      tmp.path,
    ]);
    if (r.exitCode != 0) throw StateError('dart format failed: ${r.stderr}');
    return tmp.readAsStringSync().replaceAll('\r\n', '\n');
  } finally {
    dir.deleteSync(recursive: true);
  }
}

void main(List<String> args) {
  final source = File('../design-system/project/tokens.json');
  final out = File('lib/core/design_system/tokens.g.dart');
  final text = formatted(
    generate(jsonDecode(source.readAsStringSync()) as Map<String, dynamic>),
  );
  if (args.contains('--check')) {
    final same =
        out.existsSync() &&
        out.readAsStringSync().replaceAll('\r\n', '\n') == text;
    stdout.writeln(
      same
          ? 'tokens.g.dart is current'
          : 'tokens.g.dart is stale: run dart run tool/gen_tokens.dart',
    );
    exit(same ? 0 : 1);
  }
  out.createSync(recursive: true);
  out.writeAsStringSync(text);
  stdout.writeln('wrote ${out.path}');
}
