"""Generates Finly's Android launcher, notification and splash resources from the brand geometry.

Source of truth: design-system/project/assets/Logos/finly-launcher-*.svg (108-unit canvas; the glyph is the "F" path
with round caps and the coin). The geometry below is those SVGs' transform applied once, so the vector drawables match
the logo exactly. Colours come from the logo tokens (logo-tile, logo-glyph, logo-coin) and surface.

Run from app/:  python tool/gen_launcher.py
Writes: res/drawable/ic_launcher_foreground.xml, ic_launcher_monochrome.xml, ic_notification.xml, launch_background.xml
        (+ night), res/mipmap-anydpi-v26/ic_launcher.xml, res/mipmap-*/ic_launcher.png (Android 7.x, no adaptive icons),
        res/values*/colors.xml, res/values-v31*/styles.xml (Android 12+ splash).
"""
import json
import os

from PIL import Image, ImageDraw

RES = 'android/app/src/main/res'
TOKENS = json.load(open('../design-system/project/tokens.json', encoding='utf-8'))
COLORS = {t['name']: t['value'] for t in TOKENS['color']['tokens']}


def color(name, theme='light'):
    v = COLORS[name]
    return (v[theme] if isinstance(v, dict) else v).upper()


# The glyph on the 108 canvas: translate(54 54) scale(1.6) translate(-24 -24) applied to the logo path.
def p(x, y):
    return (54 + 1.6 * (x - 24), 54 + 1.6 * (y - 24))


STROKES = [(p(16, 13), p(16, 35)), (p(16, 13), p(32, 13)), (p(16, 23.5), p(27, 23.5))]
STROKE_W = 5.5 * 1.6
COIN_C = p(31, 34)
COIN_R = 3.75 * 1.6


def fmt(v):
    return f'{v:.2f}'.rstrip('0').rstrip('.')


def path_data():
    return ' '.join(f'M{fmt(a[0])},{fmt(a[1])} L{fmt(b[0])},{fmt(b[1])}' for a, b in STROKES)


def coin_data(cx, cy, r):
    return f'M{fmt(cx - r)},{fmt(cy)} a{fmt(r)},{fmt(r)} 0 1,0 {fmt(2 * r)},0 a{fmt(r)},{fmt(r)} 0 1,0 {fmt(-2 * r)},0'


def vector(glyph, coin, size=108):
    return f'''<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by app/tool/gen_launcher.py from design-system/project/assets/Logos. Do not edit by hand. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{size}dp" android:height="{size}dp"
    android:viewportWidth="108" android:viewportHeight="108">
    <path android:pathData="{path_data()}" android:strokeColor="{glyph}" android:strokeWidth="{fmt(STROKE_W)}"
        android:strokeLineCap="round" android:strokeLineJoin="round" android:fillColor="#00000000"/>
    <path android:pathData="{coin_data(COIN_C[0], COIN_C[1], COIN_R)}" android:fillColor="{coin}"/>
</vector>
'''


def write(rel, text):
    path = os.path.join(RES, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        f.write(text)


def legacy_png(px):
    """Android 7.x has no adaptive icons: a rounded tile with the glyph, drawn at 4x and downsampled for smooth edges."""
    s = 4
    big = px * s
    img = Image.new('RGBA', (big, big), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    tile = tuple(int(color('logo-tile')[i:i + 2], 16) for i in (1, 3, 5))
    inset = big * 0.04
    d.rounded_rectangle([inset, inset, big - inset, big - inset], radius=big * 0.22, fill=tile + (255,))
    # The 108 canvas maps onto the tile; keep the glyph inside the same visual weight as the adaptive icon.
    k = big / 108 * 1.12
    off = (big - 108 * k) / 2

    def q(pt):
        return (off + pt[0] * k, off + pt[1] * k)

    w = STROKE_W * k
    for a, b in STROKES:
        d.line([q(a), q(b)], fill=(255, 255, 255, 255), width=round(w))
        for c in (a, b):
            cx, cy = q(c)
            d.ellipse([cx - w / 2, cy - w / 2, cx + w / 2, cy + w / 2], fill=(255, 255, 255, 255))
    coin = tuple(int(color('logo-coin')[i:i + 2], 16) for i in (1, 3, 5))
    cx, cy = q(COIN_C)
    r = COIN_R * k
    d.ellipse([cx - r, cy - r, cx + r, cy + r], fill=coin + (255,))
    return img.resize((px, px), Image.LANCZOS)


def main():
    write('drawable/ic_launcher_foreground.xml', vector(color('logo-glyph'), color('logo-coin')))
    write('drawable/ic_launcher_monochrome.xml', vector('#FFFFFF', '#FFFFFF'))
    write('drawable/ic_notification.xml', vector('#FFFFFF', '#FFFFFF', size=24))
    write('mipmap-anydpi-v26/ic_launcher.xml', '''<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by app/tool/gen_launcher.py. Android 8+ adaptive icon; Android 13+ themed icon via monochrome. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/finly_logo_tile"/>
    <foreground android:drawable="@drawable/ic_launcher_foreground"/>
    <monochrome android:drawable="@drawable/ic_launcher_monochrome"/>
</adaptive-icon>
''')
    for theme, folder in (('light', 'values'), ('dark', 'values-night')):
        write(f'{folder}/colors.xml', f'''<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by app/tool/gen_launcher.py from design-system tokens. -->
<resources>
    <color name="finly_logo_tile">{color('logo-tile', theme)}</color>
    <color name="finly_surface">{color('surface', theme)}</color>
</resources>
''')
    launch = '''<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by app/tool/gen_launcher.py. Launch screen before Android 12: the Finly tile on the surface colour. -->
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:drawable="@color/finly_surface"/>
    <item android:gravity="center" android:width="96dp" android:height="96dp">
        <shape android:shape="oval"><solid android:color="@color/finly_logo_tile"/></shape>
    </item>
    <item android:gravity="center" android:width="108dp" android:height="108dp"
        android:drawable="@drawable/ic_launcher_foreground"/>
</layer-list>
'''
    write('drawable/launch_background.xml', launch)
    write('drawable-v21/launch_background.xml', launch)
    for folder, parent in (('values-v31', 'Theme.Light.NoTitleBar'), ('values-night-v31', 'Theme.Black.NoTitleBar')):
        write(f'{folder}/styles.xml', f'''<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by app/tool/gen_launcher.py. Android 12+ system splash with the Finly icon. -->
<resources>
    <style name="LaunchTheme" parent="@android:style/{parent}">
        <item name="android:windowSplashScreenBackground">@color/finly_surface</item>
        <item name="android:windowSplashScreenAnimatedIcon">@drawable/ic_launcher_foreground</item>
        <item name="android:windowSplashScreenIconBackgroundColor">@color/finly_logo_tile</item>
        <item name="android:windowBackground">@drawable/launch_background</item>
    </style>
    <style name="NormalTheme" parent="@android:style/{parent}">
        <item name="android:windowBackground">?android:colorBackground</item>
    </style>
</resources>
''')
    for folder, px in (('mipmap-mdpi', 48), ('mipmap-hdpi', 72), ('mipmap-xhdpi', 96), ('mipmap-xxhdpi', 144),
                       ('mipmap-xxxhdpi', 192)):
        os.makedirs(os.path.join(RES, folder), exist_ok=True)
        legacy_png(px).save(os.path.join(RES, folder, 'ic_launcher.png'), optimize=True)
    # A preview for review (not packaged).
    os.makedirs('build', exist_ok=True)
    legacy_png(512).save('build/launcher_preview.png')
    print('ok')


if __name__ == '__main__':
    main()
